name: Articulate Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest
    
    env:
      Solution_File: src\Articulate.sln
      Solution_Info: src\SolutionInfo.cs
      Web_Proj_Folder: src\Articulate.Web
      Nuspec: build\Articulate.nuspec
      Release_Folder: build\Release
      Configuration: Release
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    
    - name: Configure SolutionInfo
      run: |
        # Set the version number in SolutionInfo.cs
        $SolutionInfoPath = Get-Item $Env:SOLUTION_INFO
        (gc -Path $SolutionInfoPath) `
          -replace "(?<=Version\(`")[.\d]*(?=`"\))", $ReleaseVersionNumber |
          Set-Content -Path $SolutionInfoPath -Encoding UTF8
        (gc -Path $SolutionInfoPath) `
          -replace "(?<=AssemblyInformationalVersion\(`")[.\w-]*(?=`"\))", "$ReleaseVersionNumber$PreReleaseName" |
          Set-Content -Path $SolutionInfoPath -Encoding UTF8
        # Set the copyright
        $Copyright = "Copyright " + [char]0x00A9 + " Shannon Deminick " + (Get-Date).year
        (gc -Path $SolutionInfoPath) `
          -replace "(?<=AssemblyCopyright\(`").*(?=`"\))", $Copyright |
          Set-Content -Path $SolutionInfoPath -Encoding UTF8;
      shell: pwsh

    - name: Nuget Restore
      run: nuget restore $env:Solution_File
    
    - name: MSBuild Clean
      run: msbuild $env:Solution_File /p:Configuration=Release /t:Clean
    
    - name: MSBuild Build
      run: msbuild $env:Solution_File /p:Configuration=$env:Configuration

    #- name: Nuget Pack
    #  run: nuget pack $env:Nuspec -BasePath $env:Web_Proj_Folder -OutputDirectory $env:Release_Folder -Version "$ReleaseVersionNumber$PreReleaseName" -Properties "copyright=$Copyright;buildFolder=$BuildFolder"
